[package]
name = "rust-async"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["blocking", "json"] }
thiserror = "1.0"
tokio = { version = "1.39", features = ["full"] }
